name: jobfit
description: "A new Flutter project."

# Prevent accidental publishing
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  animated_text_kit: ^4.2.3
  just_audio: ^0.10.4
  confetti: ^0.8.0
  url_launcher: ^6.3.1
  share_plus: ^11.0.0
  smooth_page_indicator: ^1.2.1
  font_awesome_flutter: ^10.8.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - assets/data/
    - assets/icon/

# â— DO NOT put this inside the flutter: block
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/job_finder_final_logo.png"
